defmodule AcmeUdpLogger.Repo.Migrations.AddPacket144Table do
  use Ecto.Migration

  def change do
    create table(:packet144) do
      add :options_byte, :integer
      add :mobile_id_length, :integer
      add :mobile_id, :string
      add :mobile_id_type_length, :integer
      add :mobile_id_type, :integer
      add :service_type, :integer
      add :message_type, :integer
      add :sequence, :integer
      add :update_time, :utc_datetime
      add :time_of_fix, :utc_datetime
      add :latitude, :string
      add :longitude, :string
      add :altitude, :integer
      add :speed, :integer
      add :heading, :integer
      add :satellites, :integer
      add :fix_status, :integer
      add :carrier, :integer
      add :rssi, :integer
      add :comm_state, :integer
      add :hdop, :integer
      add :inputs, :integer
      add :unit_status, :integer
      add :app_msg_type, :integer
      add :app_msg_len, :integer
      add :map_id, :integer
      add :jpod_mach_state, :integer
      add :map_id_rev_con, :integer
      add :odometer_length, :integer
      add :odometer_1708, :float
      add :odometer_1939, :float
      add :odometer_hi_rez, :float
      add :batt_volt_1708, :float
      add :batt_volt_1939, :float
      add :sw_batt_volt_1708, :float
      add :sw_batt_volt_1939, :float
      add :engine_speed_1708, :float
      add :engine_speed_1939, :float
      add :wheel_based_speed, :float
      add :parking_brake, :integer
      add :brake_pedal_switch_1708, :integer
      add :cruze_control_spd, :integer
      add :eng_coolant_tmp_1708, :float
      add :eng_coolant_tmp_1939, :float
      add :eng_coolant_pres_1708, :float
      add :eng_coolant_pres_1939, :float
      add :eng_coolant_lvl_1708, :float
      add :eng_coolant_lvl_1939, :float
      add :eng_oil_tmp_1708, :float
      add :eng_oil_tmp_1939, :float
      add :eng_oil_pres_1708, :float
      add :eng_oil_pres_1939, :float
      add :eng_crank_pres_1708, :float
      add :eng_crank_pres_1939, :float
      add :eng_oil_lvl_1708, :float
      add :eng_oil_lvl_1939, :float
      add :eng_fuel_lvl_1_1708, :float
      add :eng_fuel_lvl_1_1939, :float
      add :eng_fuel_lvl_2_1708, :float
      add :eng_fuel_lvl_2_1939, :float
      add :seatbelt_switch, :integer
      add :eng_inst_fuel_econ_1708, :float
      add :eng_inst_fuel_econ_1939, :float
      add :eng_fuel_rate_1708, :float
      add :eng_fuel_rate_1939, :float
      add :hi_rez_eng_fuel_rate_1939, :float
      add :transmission_gear_1939, :integer
      add :accel_pedal_position_1708, :float
      add :accel_pedal_position_1939, :float
      add :brake_pedal_position_1939, :float
      add :turn_signal, :integer
      add :transmission_curr_range_1939, :integer
      add :percent_eng_load_1939, :float
      add :percent_eng_torque_1939, :float
      add :def_tank_lvl_1939, :float
      timestamps
    end
  end
end
